name: buildx
description: BuildX - Construction Expense, Approval & Invoice Generation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  uuid: ^4.5.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  pdf: ^3.11.1
  printing: ^5.13.4

flutter:
  uses-material-design: true
